baseURL = "https://cispec.org/"
languageCode = "en-GB"
title = "cispec"
theme = "hugo-book"

enableGitInfo = true
disableKinds  = ["taxonomy", "term"]

[params]
  description   = "The org.cispec namespace: a public Change Item attribution standard for software supply chains."
  organisation  = "Da Planet Security"
  pen           = "42387"
  duns          = "039-271-257"
  specVersion   = "1.0"
  licenceSPDX   = "BSD-2-Clause"
  repoCanonical = "https://github.com/denzuko/cispec"
  predecessor   = "net.matrix"

  # hugo-book
  BookRepo     = "https://github.com/denzuko/cispec"
  BookEditPath = "edit/main/content"
  BookSection  = "*"
  BookToC      = true
  BookSearch   = true
  BookTheme    = "auto"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style     = "monokai"
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 4
